syntax = "proto3";

package task;

service TaskService {
  rpc AddTask (AddTaskRequest) returns (TaskResponse);
  rpc GetTask (GetTaskRequest) returns (TaskResponse);
  rpc StreamMicroTasks (MicroTaskRequest) returns (stream MicroTask);
}

message AddTaskRequest {
  string title            = 1;
  string description      = 2;
  int32  priority         = 3;
  int32  duration_minutes = 4;
}

message GetTaskRequest {
  string task_id = 1;
}

message MicroTaskRequest {
  string task_id = 1;
}

message TaskResponse {
  string task_id = 1;
  string title   = 2;
  bool   success = 3;
  string message = 4;
}

message MicroTask {
  string micro_id         = 1;
  string task_id          = 2;
  string step_title       = 3;
  int32  step_number      = 4;
  int32  duration_minutes = 5;
  bool   is_last          = 6;
}